trigger:
- main

variables:
  BUILD_NUMBER: v$(GitVersion.Major).$(GitVersion.Minor)

pool:
  vmImage: ubuntu-latest

jobs:
  - job: CalculateVersion
    displayName: Tagging release version
  
    steps:
      - checkout: self

      - task: Maven@3
        displayName: 'Test defaultApp'
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
#          codeCoverageToolOption: JaCoCo
#          codeCoverageClassFilesDirectories: $(SourceDirectory)/target/classes,$(SourceDirectory)/target/test-classes
#          codeCoverageSourceDirectories: $(SourceDirectory)/src/main/java,$(SourceDirectory)/src/test
          goals: 'test'

      - task: Maven@3
        displayName: 'Publish Artifact'
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          mavenAuthenticateFeed: true
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
#          codeCoverageToolOption: JaCoCo
#          codeCoverageClassFilesDirectories: $(SourceDirectory)/target/classes,$(SourceDirectory)/target/test-classes
#          codeCoverageSourceDirectories: $(SourceDirectory)/src/main/java,$(SourceDirectory)/src/test
          goals: 'deploy'
