pool:
  vmImage: ubuntu-latest

resources:
  pipelines:
    - pipeline: pipelineresource  # nome della risorsa pipeline
      source: azure-pipelines     # nome della pipeline referenziata da qesta risorsa
      project: defaultApp
      trigger:                    # esegue questa pipeline ogni volta che quella referenziata termina
        branches:
          include:
            - develop

jobs:
  - job: JobName
    steps:
    - task: CmdLine@2
      inputs:
        script: 'echo Execution of main-pipeline.yml'
