trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

resources:
  pipelines:
    - pipeline: pipelineResource  
      source: first-pipelines     
      project: defaultApp
      trigger:                   
        branches:
          include:
            - main

jobs:
  - job: JobName
    steps:
    - task: CmdLine@2
      inputs:
        script: 'echo Execution of second-pipeline.yml'
